config/routes.rb
Rails.application.routes.draw do
  root "themes#index"
  # get 'likes/create'
  # get 'likes/destroy'

  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :users, only: [:show]
  resources :themes do
    resource :likes, only: [:create, :destroy]
    resources :answers, only: [:create,:destroy] do
      resource :favorites, only: [:create, :destroy]
    end
end

end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :answer, presence: true
  belongs_to :user 
  belongs_to :theme
  has_many :favorites, dependent: :destroy

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
  # def self.create_all_ranks #Answerクラスからデータを取ってくる処理なのでクラスメソッド！
  #   Answer.find(Favorite.group(:answer_id).order('count(answer_id) desc').limit(3).pluck(:answer_id))
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :answer
    belongs_to :theme
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :theme
end

app/models/theme.rb
class Theme < ApplicationRecord
    validates :content, presence: true
    mount_uploader :image, ImageUploader
    belongs_to :user 
    has_many :answers, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :likes, dependent: :destroy

    def liked_by?(user)
        likes.where(user_id: user.id).exists?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader
  
  validates :profile, length: { maximum: 200 } #追記
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :themes, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_themes, through: :likes, source: :theme


  def self.guest
    find_or_create_by(email: "tesuser@example.com",username: "testuser") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_find

  def create
    @answer = @theme.answers.new(answer_params)
    @answer.user_id = current_user.id
    if @answer.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @answer = @theme.answers.find(params[:id])
    @answer.destroy
    redirect_back(fallback_location: root_path)
  end

  private
    def set_find
      @theme = Theme.find(params[:theme_id])
    end

    def answer_params
      params.require(:answer).permit(:answer)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation,:image ,:profile ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs

  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(answer_id: params[:answer_id],theme_id: params[:theme_id])
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    favorite = Favorite.find_by(answer_id: params[:answer_id], user_id: current_user.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.build(theme_id: params[:theme_id])
    like.save
    redirect_to themes_path
  end

  def destroy
    like = Like.find_by(theme_id: params[:theme_id], user_id: current_user.id)
    like.destroy
    redirect_to themes_path
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :authenticate_user! ,except: [:index]  

  def index
    @themes = Theme.all.order(created_at: :desc)
    @all_ranks = Theme.find(Like.group(:theme_id).order('count(theme_id) desc').limit(3).pluck(:theme_id))
  end

  def new
    @theme = Theme.new
  end

  def create 
    theme = Theme.new(theme_params)
    theme.user_id = current_user.id
    if theme.save
      flash[:notice] = "投稿が完了しました"
      redirect_to :action => :index
    else
      redirect_to :action => :new
    end
  end

  def show
    @theme = Theme.find(params[:id])
    @answers = @theme.answers
    @all_ranks = Answer.find(Favorite.where(theme_id: params[:id]).group(:answer_id).order('count(answer_id) desc').limit(3).pluck(:answer_id))
  end

  def edit
    @theme = Theme.find(params[:id])
  end

  def update
    @theme = Theme.find(params[:id])
    if @theme.update(theme_params)
      flash[:notice] = "編集しました"
      redirect_to :action => :show , :id => @theme.id
    else
      render :action => :edit
    end
  end

  def destroy
    Theme.find(params[:id]).destroy
    flash[:notice] = "削除しました"
    redirect_to :action => :index
  end

  # def new_guest
  #   user = User.find_or_create_by!(email: 'testuser@test.com') do |user|
  #     user.password = SecureRandom.urlsafe_base64
  #     # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
  #   end
  #   sign_in user
  #   redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  # end


  private
        def theme_params
            params.require(:theme).permit(:content,:image)
        end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    def new_guest
      user = User.guest
      sign_in user
      redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @themes = @user.themes
    @like_themes = @user.like_themes 
  end

  # def new_guest
  #   user = User.guest
  #   sign_in user
  #   redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  # end

    private
      def user_params
          params.require(:theme).permit(:content,:image,:profile)
      end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ogiri</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/31544c68e6.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans+JP">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "responsive", :media => "all" %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        <%= link_to root_path do%>
          <i class="navbar-brand">大喜利道場</i>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "ギャラリー", themes_path, class: "nav-link", tabindex: "-1" %>
                </li>
                <li class="nav-item">
                  <%= link_to "お題作成", new_theme_path, class: "nav-link", tabindex: "-1" %>
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ", user_path(current_user.id), class: "nav-link", tabindex: "-1" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link", tabindex: "-1" %>
                </li>
            <% else %>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: "nav-link", tabindex: "-1" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: "nav-link", tabindex: "-1" %>
                </li>
            <% end %>
            </ul>
        </div>
      </nav>
    </header>
      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice]%>
        </div>
      <% end %>
    <%= yield %>
    
  
  </body>
</html>

app/views/themes/edit.html.erb
<div class="themes-edit main">
  <div class="themes-edit container">
    <p>投稿フォーム</p>
    <%= form_with model: @theme, url: { action: :update }, class: "new_list", local: true do |f| %>
      <% if @theme.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :content , "お題"%>
      <%= f.text_area :content, autofocus: true, class: "form-control listName", placeholder: "入力してください" %>
      <div class="field">
        <%= f.label :image, "画像送信" %>
        <%= f.file_field :image %>
      </div>
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/themes/index.html.erb
<div class="themes-index main">
    <div class="t-container">
        <div class="post-link-block">
            <%= link_to new_theme_path,class: "post-link"  do %>
                <i class="fas fa-plus">お題作成</i>
            <% end %>
        </div>
    <hr>
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">ギャラリー</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">ランキング</a>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
            <div class="index">
                <% @themes.each do |t| %>
                    <div class="theme">
                        <div class="image-theme">
                            <% if t.image? %>
                                <%= image_tag t.image.url ,size: "250x200" ,class: "t_img"%>
                            <% else %>
                                <%= image_tag "oogiri.png" ,size: "250x200" ,class: "default_t_img"%>
                            <%end%>
                        </div>
                        <div class="theme-content"><p class="theme-font"><%= t.content %></p></div>
                        <div class="t-user_info">
                            <p><%= time_ago_in_words(t.created_at) %>前</p>
                            <p class= "user-font"><img src=<%= t.user.image.url %> class = "t-icon_image">
                            <%= link_to t.user.username, user_path(t.user.id) ,class: "user_link" %></p>
                        </div>
                        <!-- 追加 -->
                        <div class="good">
                            <% if user_signed_in? %>
                                <% if t.liked_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
                                    <%=link_to theme_likes_path(t.id) ,method: :delete do %>
                                        <i class="far fa-thumbs-up good-btn"></i><%= t.likes.count %>
                                    <% end %>
                                <% else %>
                                    <%=link_to theme_likes_path(t.id),method: :post do %>
                                        <i class="far fa-thumbs-up ungood-btn"></i><%= t.likes.count %>
                                    <% end %>
                                <% end %>
                            <% else %>
                                <p><span>お気に入り数: </span><%= t.likes.count %></p>
                            <% end %>
                        <!-- ここまで　-->
                        </div>
                    <hr>
                        <div class="link-form">
                            <div class="link">
                                <%= link_to "回答する",theme_path(t.id),class: "answer-btn"%>
                            </div>
                        </div>
                        <% if t.user == current_user %>
                                <%# <%= link_to "お題を編集する",edit_theme_path(t.id) %> 
                            <%= link_to theme_path(t.id) ,method: :delete, class: "d delete-btn" do %>
                                <i class="far fa-trash-alt">消去</i>
                            <% end %>
                        <% end %>
                    </div>
                    <hr>
                <% end %>
            </div>
        </div>
        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            <div class="ranking">
                <% lastLike = 0 %>
                <% j = 1 %>
                <% @all_ranks.each.with_index(1) do |theme, i| %>
                    <div class="theme">
                        <div class="image-theme">
                    <!--順位表示-->
                        <% if i == 1 %>
                            <% lastLike = theme.likes.count %>
                        <% end %>
                        <% if theme.likes.count != lastLike %>
                            <% j = i %>
                            <h3>第<%= j %>位</h3>
                            <% lastLike = theme.likes.count %>
                        <% else %>
                            <% lastLike = theme.likes.count %>
                            <h3>第<%= j %>位</h3>
                        <% end %>
                    <!--順位表示-->
                            <% if theme.image? %>
                                <%= image_tag theme.image.url ,size: "250x200" ,class: "t_img"%>
                            <% else %>
                                <%= image_tag "oogiri.png" ,size: "250x200" ,class: "default_t_img"%>
                            <%end%>
                        </div>
                        <div class="theme-content"><p class="theme-font"><%= theme.content %></p></div>
                        <div class="t-user_info">
                            <p><%= time_ago_in_words(theme.created_at) %>前</p>
                            <p class= "user-font"><img src=<%= theme.user.image.url %> class = "t-icon_image">
                            <%= link_to theme.user.username, user_path(theme.user.id) ,class: "user_link" %></p>
                        </div>
                        <div class="good">
                            <% if user_signed_in? %>
                                <i class="far fa-thumbs-up good-btn"></i><%= theme.likes.count %>
                            <% end %>
                        </div>
                    </div>
                    <hr>
                <% end%>
            </div>
        </div>
    </div>
            
        
    </div>
</div>

app/views/themes/new.html.erb
<div class="themes-new main">
  <div class="themes-new container">
    <div class="theme-info">
      <h2>使い方</h2>
    </div>
    <div class="themes-new rule">
      <ul>
        <li>・投稿フォームにお題を記入</li>
        <li>・画像をお題にされる方は、画像選択ボタンからファイルを選択してください</li>
        <li>・お題作成のボタンを押すとお題が投稿されます</li>
      </ul>
    </div>
    <div class="theme-info">
      <h2>投稿フォーム</h2>
    </div>
    <div class="themes-new contents">
      <%= form_with model: @theme, url: { action: :create }, class: "new_list", local: true do |f| %>
        <% if @theme.errors.any? %>
          <p class="text-danger">1～255文字以内で入力してください</p>
        <% end %>
        <div class="form-group">
          <%= f.label :content , "お題"%>
          <%= f.text_area :content, autofocus: true, class: "form-control listName", placeholder: "1文字以上入力してください" %>
        </div>
        <div class="form-group">
          <%= f.label :image, "画像" %><br>
          <%= f.file_field :image %>
        </div>
        <div class="text-center"><%= f.submit "お題作成", class: "submitBtn" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/themes/show.html.erb
<div class="themes-show main">
  <div class="t-container">
    <% if @theme.user == current_user %>
      <%# <li><%= link_to "お題を編集する",edit_theme_path(@theme.id)</li> %> 
      <%= link_to theme_path(@theme.id) ,method: :delete ,class: "post-link" do %>
        <i class="far fa-trash-alt">お題消去</i>
      <% end %>
    <% end %>
  <hr>
  <div class="theme-info">
    <h2>お題</h2>
  </div>
    <div class="theme">
        <div class="image-theme">
            <% if @theme.image? %>
                <%= image_tag @theme.image_url ,size: "250x200" ,class: "t_img"%>
            <% else %>
                <%= image_tag "oogiri.png" ,size: "250x200" ,class: "default_t_img"%>
            <%end%>
        </div>
        <div class="theme-content"><p class="theme-font"><%= @theme.content %></p></div>
      <div class="t-user_info">
        <p><%=time_ago_in_words(@theme.created_at) %>前</p> 
        <p class="user-font"><img src=<%= @theme.user.image.url %> class = "t-icon_image">
        <%= link_to @theme.user.username, user_path(@theme.user.id),class:"user_link"%></p>
      </div>
    </div>
    

    <!-- answer-wrapperの中にanswer-listとanswer-ranking -->
    <div class="answer-wrapper">
      <div class="answer-list">
        <h2 class="answer-info">回答一覧</h2><hr>
        <% @answers.each do |answer| %> 
          <p class= "user-font">
            <img src=<%= answer.user.image %> class = "t-icon_image">
            <%= answer.user.username unless answer.user.blank? %>
          </p>
          <p class="theme-font"><%= answer.answer %></p><br><br>
          <% if user_signed_in? %>
            <% if answer.favorited_by?(current_user) %> 
              <%=link_to  theme_answer_favorites_path(@theme,answer.id), method: :delete do %>
                <span class="fa fa-heart like-btn"></span><%= answer.favorites.count %>
              <% end %>
            <% else %>
              <%=link_to theme_answer_favorites_path(@theme,answer.id), method: :post do %>
                <span class="fa fa-heart like-btn-unlike"></span><%= answer.favorites.count %>
              <% end %>
            <% end %>
          <% end %>
            <% if current_user == answer.user %>
              <%= link_to theme_answer_path(@theme,answer),method: :delete, class: "delete-btn" do %>
                <i class="far fa-trash-alt">消去</i>
              <% end %>
            <% end  %>
            <hr>
        <% end %>
      </div>
      <!---->
      <div class="answer-ranking">
        <h2 class="answer-info"><i class="fas fa-crown"></i>Top5</h2><hr>
        <% lastFavorite = 0 %>
        <% j = 1 %>
        <% @all_ranks.each.with_index(1) do |answer, i| %>
        <!--順位表示-->
          <% if i == 1 %>
            <% lastFavorite = answer.favorites.count %>
          <% end %>
          <% if answer.favorites.count != lastFavorite %>
            <% j = i %>
            <h3>第<%= j %>位</h3>
            <% lastFavorite = answer.favorites.count %>
          <% else %>
            <% lastFavorite = answer.favorites.count %>
            <h3>第<%= j %>位</h3>
          <% end %>
        <!--順位表示-->
          <p class= "user-font">
            <img src=<%= answer.user.image.url %> class = "t-icon_image">
            <%= answer.user.username unless answer.user.blank? %>
          </p>
          <p class="theme-font"><%= answer.answer %></p><br><br>
          <% if user_signed_in? %>
            <span class="fa fa-heart like-btn"></span><%= answer.favorites.count %></p><hr>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- answer-wrapperの中にanswer-listとanswer-ranking -->

    <div class="answer-form">
      <% if user_signed_in? %>
        <%= form_with(model: [@theme, @theme.answers.build], local: true) do |f| %>
        <div class="mb-3">
          <%= f.text_area :answer,autofocus: true,class: "form-control"%>
        </div>
          <%= button_tag type: "submit", class: "submitBtn" do %>
            <i class="far fa-comments"></i> 回答する
          <% end %>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="main">
  <div class="u-container">
    <% if current_user == @user %>
      <%= link_to edit_user_registration_path ,class: "post-link" do %>
        <span class="fas fa-user-edit"></span>
      <% end %>
    <% end %>
  <hr>
  <div class="users-wrapper">
    <div class="wrapper_user">
      <div class="user-head">
        <h2>プロフィール</h2>
      </div>
      <div class="user-introduce">
        <div class="user">
          <p class ="user-img"><img src=<%= @user.image.url %> class = "icon_image"></p>
          <p class="user-font name"><%= @user.username %></p>    
        </div>
        <div class="user-profile">
          <h2>自己紹介</h2>
          <%= @user.profile %>
        </div>
      </div>
    </div>
    <div class="wrapper_info">
      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Good済み</a>
          <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">投稿一覧</a>
        </div>
      </nav>
        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
              <% @like_themes.each do |theme| %>
                <div class="theme">
                  <div class="image-theme">
                  <% if theme.image? %>
                      <%= link_to (image_tag theme.image_url,class: "t_img") ,theme_path(theme.id)%>
                  <% else %>
                      <%= link_to (image_tag "oogiri.png" ,class: "default_t_img" ) ,theme_path(theme.id)%>
                  <%end%>  
                  </div>
                  <div class="theme-content"><p class= "theme-font"><%= theme.content %></p></div>
                <hr>
                  <div class="link-form">
                    <div class="link">
                      <%= link_to "回答する",theme_path(theme.id),class: "answer-btn"%>
                    </div>
                  </div>
                  <% if theme.user == current_user %>
                    <%= link_to theme_path(theme.id) ,method: :delete, class: "d delete-btn" do %>
                      <i class="far fa-trash-alt">消去</i>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
          </div>
          <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
              <% @themes.each do |theme| %>
                <div class="theme">
                  <div class="image-theme">
                    <% if theme.image? %>
                        <%= link_to (image_tag theme.image_url,class: "t_img") ,theme_path(theme.id)%>
                    <% else %>
                        <%= link_to (image_tag "oogiri.png" ,class: "default_t_img" ) ,theme_path(theme.id)%>
                    <%end%>                 
                  </div>
                  <div class="theme-content"><p class= "theme-font"><%= theme.content %></p></div>
              <hr>
                  <div class="link-form">
                    <div class="link">
                      <%= link_to "回答する",theme_path(theme.id),class: "answer-btn"%>
                    </div>
                  </div>
                  <% if theme.user == current_user %>
                    <%= link_to theme_path(theme.id) ,method: :delete, class: "d delete-btn" do %>
                      <i class="far fa-trash-alt">消去</i>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>